/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PromoterResponse } from '../../models/promoter-response';

export interface FindStaffByEmail$Params {

/**
 * Email du promoteur
 */
  email: string;
}

export function findStaffByEmail(http: HttpClient, rootUrl: string, params: FindStaffByEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<PromoterResponse>> {
  const rb = new RequestBuilder(rootUrl, findStaffByEmail.PATH, 'get');
  if (params) {
    rb.query('email', params.email, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PromoterResponse>;
    })
  );
}

findStaffByEmail.PATH = '/promoter/find-by-email';
