/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PromoterResponse } from '../../models/promoter-response';

export interface GetPromoterById$Params {

/**
 * ID du promoteur
 */
  promoterId: number;
}

export function getPromoterById(http: HttpClient, rootUrl: string, params: GetPromoterById$Params, context?: HttpContext): Observable<StrictHttpResponse<PromoterResponse>> {
  const rb = new RequestBuilder(rootUrl, getPromoterById.PATH, 'get');
  if (params) {
    rb.path('promoterId', params.promoterId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PromoterResponse>;
    })
  );
}

getPromoterById.PATH = '/promoter/{promoterId}';
