/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponsePromoterResponse } from '../../models/page-response-promoter-response';

export interface GetAllStaffs$Params {

/**
 * Offset de pagination
 */
  offset?: number;

/**
 * Taille de page
 */
  pageSize?: number;

/**
 * Champ de tri
 */
  field?: string;

/**
 * Ordre de tri
 */
  order?: boolean;
}

export function getAllStaffs(http: HttpClient, rootUrl: string, params?: GetAllStaffs$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponsePromoterResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllStaffs.PATH, 'get');
  if (params) {
    rb.query('offset', params.offset, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('field', params.field, {});
    rb.query('order', params.order, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponsePromoterResponse>;
    })
  );
}

getAllStaffs.PATH = '/promoter/get-all';
