/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface NationalIdCardFileUpload$Params {
  validUntil: string;
  nationalIdNumber: string;
      body?: {

/**
 * idCard file Upload
 */
'file': Blob;
}
}

export function nationalIdCardFileUpload(http: HttpClient, rootUrl: string, params: NationalIdCardFileUpload$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, nationalIdCardFileUpload.PATH, 'post');
  if (params) {
    rb.query('validUntil', params.validUntil, {});
    rb.query('nationalIdNumber', params.nationalIdNumber, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

nationalIdCardFileUpload.PATH = '/promoter/nationalId/{validUntil}';
