/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseSubjectResponse } from '../../models/page-response-subject-response';
import { SpecialitySubjectRequest } from '../../models/speciality-subject-request';

export interface GetAllSubjectOfSpeciality$Params {
  specialitySubjectRequest: SpecialitySubjectRequest;
  offset?: number;
  pageSize?: number;
  field?: string;
  order?: boolean;
}

export function getAllSubjectOfSpeciality(http: HttpClient, rootUrl: string, params: GetAllSubjectOfSpeciality$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseSubjectResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllSubjectOfSpeciality.PATH, 'get');
  if (params) {
    rb.query('specialitySubjectRequest', params.specialitySubjectRequest, {});
    rb.query('offset', params.offset, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('field', params.field, {});
    rb.query('order', params.order, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseSubjectResponse>;
    })
  );
}

getAllSubjectOfSpeciality.PATH = '/subjects/get-all';
