/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeactivateTrainingCenter$Params {

/**
 * Numéro d'accord
 */
  agreementNumber: string;
}

export function deactivateTrainingCenter(http: HttpClient, rootUrl: string, params: DeactivateTrainingCenter$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deactivateTrainingCenter.PATH, 'patch');
  if (params) {
    rb.path('agreementNumber', params.agreementNumber, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

deactivateTrainingCenter.PATH = '/trainingcenter/deactivate/{agreementNumber}';
