/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TrainingCenterResponse } from '../../models/training-center-response';

export interface GetTrainingCenterByAgreementNumber$Params {

/**
 * Numéro d'accord
 */
  agreementNumber: string;
}

export function getTrainingCenterByAgreementNumber(http: HttpClient, rootUrl: string, params: GetTrainingCenterByAgreementNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<TrainingCenterResponse>> {
  const rb = new RequestBuilder(rootUrl, getTrainingCenterByAgreementNumber.PATH, 'get');
  if (params) {
    rb.query('agreementNumber', params.agreementNumber, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TrainingCenterResponse>;
    })
  );
}

getTrainingCenterByAgreementNumber.PATH = '/trainingcenter/get-training-by-agreement-number';
