/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateTrainingCenterRequest } from '../../models/update-training-center-request';

export interface UpdatePromoter$Params {
  fullname: string;
      body: UpdateTrainingCenterRequest
}

export function updatePromoter(http: HttpClient, rootUrl: string, params: UpdatePromoter$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, updatePromoter.PATH, 'patch');
  if (params) {
    rb.path('fullname', params.fullname, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

updatePromoter.PATH = '/trainingcenter/update-trainingCenter/{fullname}';
