/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { Application } from './models/application';
export { ApplicationRequest } from './models/application-request';
export { AuthenticationRequest } from './models/authentication-request';
export { AuthenticationResponse } from './models/authentication-response';
export { Campus } from './models/campus';
export { CampusResponse } from './models/campus-response';
export { Candidate } from './models/candidate';
export { CandidateRegistrationRequest } from './models/candidate-registration-request';
export { CandidateRequest } from './models/candidate-request';
export { CandidateResponse } from './models/candidate-response';
export { Course } from './models/course';
export { CourseRequest } from './models/course-request';
export { CreateCampusRequest } from './models/create-campus-request';
export { CreatePromoterAndCenterRequest } from './models/create-promoter-and-center-request';
export { CreatePromoterRequest } from './models/create-promoter-request';
export { CreateSpecialityRequest } from './models/create-speciality-request';
export { CreateStaffRequest } from './models/create-staff-request';
export { CreateSubjectRequest } from './models/create-subject-request';
export { CreateTainingCenterRequest } from './models/create-taining-center-request';
export { Division } from './models/division';
export { GrantedAuthority } from './models/granted-authority';
export { HasSchooled } from './models/has-schooled';
export { OffersSpeciality } from './models/offers-speciality';
export { PageResponseCampusResponse } from './models/page-response-campus-response';
export { PageResponseCandidateResponse } from './models/page-response-candidate-response';
export { PageResponsePromoterResponse } from './models/page-response-promoter-response';
export { PageResponseSpecialityResponse } from './models/page-response-speciality-response';
export { PageResponseStaffResponse } from './models/page-response-staff-response';
export { PageResponseSubjectResponse } from './models/page-response-subject-response';
export { PageResponseTrainingCenterResponse } from './models/page-response-training-center-response';
export { PromoterResponse } from './models/promoter-response';
export { Role } from './models/role';
export { Speciality } from './models/speciality';
export { SpecialityRequest } from './models/speciality-request';
export { SpecialityResponse } from './models/speciality-response';
export { StaffResponse } from './models/staff-response';
export { Subject } from './models/subject';
export { SubjectRequest } from './models/subject-request';
export { SubjectResponse } from './models/subject-response';
export { TrainingCenter } from './models/training-center';
export { TrainingCenterResponse } from './models/training-center-response';
