/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { TrainingcenterService } from './services/trainingcenter.service';
export { SubjectService } from './services/subject.service';
export { StaffService } from './services/staff.service';
export { SpecialityService } from './services/speciality.service';
export { SessionService } from './services/session.service';
export { CourseService } from './services/course.service';
export { CampusService } from './services/campus.service';
export { AuthenticationService } from './services/authentication.service';
export { ApplicationService } from './services/application.service';
export { PromoterService } from './services/promoter.service';
export { CandidateService } from './services/candidate.service';
export { DivisionService } from './services/division.service';
