/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponsePaymentResponse } from '../../models/page-response-payment-response';

export interface GetAllPayments$Params {
  offset?: number;
  pageSize?: number;
  field?: string;
  order?: boolean;
}

export function getAllPayments(http: HttpClient, rootUrl: string, params?: GetAllPayments$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponsePaymentResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllPayments.PATH, 'get');
  if (params) {
    rb.query('offset', params.offset, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('field', params.field, {});
    rb.query('order', params.order, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponsePaymentResponse>;
    })
  );
}

getAllPayments.PATH = '/payment/get-all';
