/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActivateSpecialityRequest {
  dqpPrice?: number;
  examDate?: string;
  examType?: string;
  specialityName?: string;
}
