/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplicationResponse {
  amount?: number;
  applicationRegion?: string;
  applicationYear?: string;
  candidateName?: string;
  examDate?: string;
  examType?: string;
  id?: number;
  paymentMethod?: string;
  speciality?: string;
  status?: 'READYTOPAY' | 'DRAFT' | 'PAID' | 'VALIDATED' | 'INCOMPLETED' | 'REJECTED' | 'PENDING';
  paymentReceiptUrl?: string;
  cniUrl?: string;
  diplomaUrl?: string;
  photoUrl?: string;
  birthCertificateUrl?: string;
  cvUrl?: string;
  letterUrl?: string;
  financialJustificationUrl?: string;
  stageCertificateUrl?: string;
  oldApplyanceUrl?: string;
  examCenterName?: string;
  examCenterRegion?: string;
}
