/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplicationResponse {
  amount?: number;
  applicationRegion?: string;
  applicationYear?: string;
  candidateName?: string;
  id?: number;
  paymentMethod?: string;
  speciality?: string;
  status?: string;
}
