/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplicationRequest {
  academicLevel: string;
  applicationRegion?: string;
  examType?: string;
  fatherFullname: string;
  fatherProfession: string;
  motherFullname: string;
  motherProfession: string;
  speciality?: string;
  townOfResidence: string;
}
