/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Candidate } from '../models/candidate';
import { Speciality } from '../models/speciality';
export interface Application {
  actived?: boolean;
  applicationRegion?: string;
  archived?: boolean;
  candidate?: Candidate;
  createdBy?: number;
  createdDate?: string;
  endAcademicYear?: string;
  examType?: string;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  speciality?: Speciality;
  startAcademicYear?: string;
}
