/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Campus {
  actived?: boolean;
  archived?: boolean;
  capacity?: number;
  createdBy?: number;
  createdDate?: string;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  name?: string;
  quarter?: string;
  town?: string;
  xcoor?: number;
  ycoor?: number;
}
