/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CandidateRequest {
  birthCertificateUrl?: string;
  contentStatus?: 'READYTOPAY' | 'DRAFT' | 'PAID' | 'VALIDATED' | 'INCOMPLETED' | 'REJECTED' | 'PENDING';
  dateOfBirth?: string;
  email?: string;
  fatherFullName?: string;
  fatherProfession?: string;
  firstname?: string;
  highestDiplomatUrl?: string;
  highestSchoolLevel?: string;
  lastname?: string;
  motherFullName?: string;
  motherProfession?: string;
  nationalIdCardUrl?: string;
  nationalIdNumber?: string;
  nationality?: string;
  phoneNumber?: string;
  placeOfBirth?: string;
  profilePictureUrl?: string;
  sex?: string;
  townOfResidence?: string;
}

// Ajout : modèle pour la création par le centre
export interface CandidateByCenterRequest {
  firstname: string;
  lastname: string;
  email: string;
  phoneNumber: string;
  language: string;
  startYear: string;
  endYear: string;
  trainingCenterName: string;
  // Ajouter d'autres champs si besoin
}
