/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Application } from '../models/application';
import { GrantedAuthority } from '../models/granted-authority';
import { HasSchooled } from '../models/has-schooled';
import { Role } from '../models/role';
export interface Candidate {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  actived?: boolean;
  applicationList?: Array<Application>;
  archived?: boolean;
  authorities?: Array<GrantedAuthority>;
  birthCertificateUrl?: string;
  contentStatus?: 'SUBMITTED' | 'DRAFT' | 'PENDING_REVIEW' | 'APPROVED';
  createdBy?: number;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  dateOfBirth?: string;
  email?: string;
  enabled?: boolean;
  fatherFullName?: string;
  fatherProfession?: string;
  firstname?: string;
  freeCandidate?: boolean;
  hasSchooledList?: Array<HasSchooled>;
  highestDiplomatUrl?: string;
  highestSchoolLevel?: string;
  idUser?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  lastname?: string;
  motherFullName?: string;
  motherProfession?: string;
  name?: string;
  nationalIdCardUrl?: string;
  nationalIdNumber?: string;
  nationality?: string;
  password?: string;
  phoneNumber?: string;
  placeOfBirth?: string;
  profilePictureUrl?: string;
  repeatCandidate?: boolean;
  roles?: Array<Role>;
  sex?: string;
  townOfResidence?: string;
  username?: string;
}
