/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CandidateRegistrationRequest {
  email: string;
  firstname: string;
  lastname: string;
  nationalIdNumber: string;
  password?: string;
  phoneNumber: string;
  sex: string;
}
