/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CandidateRegistrationRequest {
  confirmPassword: string;
  email: string;
  endYear: string;
  firstname: string;
  language: string;
  lastname: string;
  password?: string;
  phoneNumber: string;
  sex: string;
  dateOfBirth: string;
  placeOfBirth: string;
  startYear: string;
  trainingCenterName: string;
}
