/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CandidateRequest {
  birthCertificateUrl?: string;
  contentStatus?: 'SUBMITTED' | 'DRAFT' | 'PENDING_REVIEW' | 'APPROVED';
  dateOfBirth?: string;
  email?: string;
  fatherFullName?: string;
  fatherProfession?: string;
  firstname?: string;
  highestDiplomatUrl?: string;
  highestSchoolLevel?: string;
  lastname?: string;
  motherFullName?: string;
  motherProfession?: string;
  nationalIdCardUrl?: string;
  nationalIdNumber?: string;
  nationality?: string;
  phoneNumber?: string;
  placeOfBirth?: string;
  profilePictureUrl?: string;
  sex?: string;
  townOfResidence?: string;
}
