/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Application } from '../models/application';
import { ExamCenter } from '../models/exam-center';
import { GrantedAuthority } from '../models/granted-authority';
import { HasSchooled } from '../models/has-schooled';
import { Role } from '../models/role';
export interface Candidate {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  actived?: boolean;
  applicationList?: Array<Application>;
  archived?: boolean;
  authorities?: Array<GrantedAuthority>;
  birthCertificateUrl?: string;
  contentStatus?: 'READYTOPAY' | 'DRAFT' | 'PAID' | 'VALIDATED' | 'INCOMPLETED' | 'REJECTED' | 'PENDING';
  createdBy?: number;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  cvUrl?: string;
  dateOfBirth?: string;
  departmentOfOrigin?: string;
  email?: string;
  enabled?: boolean;
  examCenter?: ExamCenter;
  fatherFullName?: string;
  fatherProfession?: string;
  financialJustificationUrl?: string;
  financialRessource?: string;
  firstname?: string;
  formationMode?: string;
  freeCandidate?: boolean;
  hasSchooledList?: Array<HasSchooled>;
  highestDiplomatUrl?: string;
  highestSchoolLevel?: string;
  idUser?: number;
  language?: string;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  lastname?: string;
  learningLanguage?: string;
  letterUrl?: string;
  matrimonialSituation?: string;
  motherFullName?: string;
  motherProfession?: string;
  name?: string;
  nationalIdCardUrl?: string;
  nationalIdNumber?: string;
  nationality?: string;
  numberOfKid?: number;
  oldApplyanceUrl?: string;
  password?: string;
  phoneNumber?: string;
  placeOfBirth?: string;
  profilePictureUrl?: string;
  regionOrigins?: string;
  repeatCandidate?: boolean;
  roles?: Array<Role>;
  sex?: string;
  stageCertificateUrl?: string;
  townOfResidence?: string;
  username?: string;
}
