/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CandidateRegistrationRequest {
  birthCertificate?: Blob;
  confirmPassword: string;
  dateOfBirth: string;
  email: string;
  fatherFullname: string;
  fatherProfession: string;
  firstname: string;
  highestDiplomat?: Blob;
  highestSchoolLevel: string;
  lastname: string;
  motherFullname: string;
  motherProfession: string;
  nationalIdCard?: Blob;
  nationalIdNumber: string;
  password?: string;
  phoneNumber: string;
  placeOfBirth: string;
  profilePicture?: Blob;
  sex: string;
  townOfResidence: string;
}
