/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SpecialityResponse } from './speciality-response';

export interface CourseResponse {
  code?: string;
  description?: string;
  name?: string;
  specialities?: SpecialityResponse[];
}
