/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SpecialityResponse } from '../models/speciality-response';
export interface CourseWithSpecialitiesResponse {
  courseId?: number;
  courseName?: string;
  specialities?: Array<SpecialityResponse>;
}
