/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Speciality } from '../models/speciality';
import { TrainingCenter } from '../models/training-center';
export interface Course {
  actived?: boolean;
  archived?: boolean;
  code?: string;
  createdBy?: number;
  createdDate?: string;
  description?: string;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  name?: string;
  priceForCqp?: number;
  specialityList?: Array<Speciality>;
  trainingCenterList?: Array<TrainingCenter>;
}
