/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateSessionRequest {
  examDate: string;
  examType: string;
  sessionYear: string;
}
