/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePromoterRequest {
  address: string;
  dateOfBirth: string;
  email: string;
  firstname: string;
  lastname: string;
  nationalIdNumber: string;
  password?: string;
  phoneNumber: string;
  schoolLevel: string;
  sex: string;
}
