/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCampusRequest {
  capacity: number;
  name: string;
  quarter: string;
  town: string;
  trainingCenterAgr: string;
  xcoor?: number;
  ycoor?: number;
}
