/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCourseAndAssignRequest {
  activitySectorName: string;
  code: string;
  description: string;
  name: string;
  priceForCqp: number;
}
