/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTainingCenterRequest {
  acronym?: string;
  agreementNumber: string;
  division: string;
  endDateOfAgreement: string;
  fullAddress: string;
  fullName: string;
  isCenterPresentCandidateForCqp?: boolean;
  isCenterPresentCandidateForDqp?: boolean;
  startDateOfAgreement: string;
}
