/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePromoterAndCenterRequest {
  approvalEnd: string;
  approvalNumber: string;
  approvalStart: string;
  birthDate: string;
  centerAcronym: string;
  centerEmail: string;
  centerName: string;
  centerPhone: string;
  centerType: string;
  city: string;
  cniNumber: string;
  cniValidUntil: string;
  confirmPassword: string;
  creationDate: string;
  departement: string;
  email: string;
  firstName: string;
  fullAddress: string;
  gender: string;
  isCenterPresentCandidateForCqp: boolean;
  isCenterPresentCandidateForDqp: boolean;
  lastName: string;
  nationality: string;
  password: string;
  phone: string;
  profession: string;
  region: string;
  residenceCity: string;
  website: string;
}
