/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateSpecialityRequest {
  code: string;
  courseId?: number;
  description: string;
  examType: string;
  name: string;
  paymentAmount?: number;
}
