/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TrainingCenter } from '../models/training-center';
export interface CreateCampusRequest {
  capacity: number;
  name: string;
  quarter: string;
  town: string;
  trainingCenter?: TrainingCenter;
  xcoor?: number;
  ycoor?: number;
}
