/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreatePromoterRequest } from '../models/create-promoter-request';
import { CreateTainingCenterRequest } from '../models/create-taining-center-request';
export interface CreatePromoterAndCenterRequest {
  promoter?: CreatePromoterRequest;
  trainingCenter?: CreateTainingCenterRequest;
}
