/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateStaffRequest {
  dateOfBirth: string;
  email: string;
  firstname: string;
  lastname: string;
  nationalIdNumber: string;
  phoneNumber: string;
  positionName: string;
}
