/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePaymenRequest {
  amount: number;
  paymentMethod: string;
  secretCode: number;
}
