/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Candidate } from '../models/candidate';
export interface ExamCenter {
  actived?: boolean;
  archived?: boolean;
  candidateList?: Array<Candidate>;
  capacity?: number;
  createdBy?: number;
  createdDate?: string;
  division?: string;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  name?: string;
  region?: string;
}
