/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HasSchooled {
  actived?: boolean;
  archived?: boolean;
  createdBy?: number;
  createdDate?: string;
  endYear?: string;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  startYear?: string;
}
