/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Speciality } from '../models/speciality';
import { TrainingCenter } from '../models/training-center';
export interface OffersSpeciality {
  actived?: boolean;
  agreement?: string;
  archived?: boolean;
  createdBy?: number;
  createdDate?: string;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  speciality?: Speciality;
  trainingCenter?: TrainingCenter;
}
