/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SpecialityResponse } from '../models/speciality-response';
export interface PageResponseSpecialityResponse {
  content?: Array<SpecialityResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
