/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExamCenterResponse } from '../models/exam-center-response';
export interface PageResponseExamCenterResponse {
  content?: Array<ExamCenterResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
