/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActivitySectorResponse } from '../models/activity-sector-response';
export interface PageResponseActivitySectorResponse {
  content?: Array<ActivitySectorResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
