/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CourseWithSpecialitiesResponse } from '../models/course-with-specialities-response';
export interface PageResponseCourseWithSpecialitiesResponse {
  content?: Array<CourseWithSpecialitiesResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
