/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Application } from '../models/application';
export interface Payment {
  actived?: boolean;
  amount?: number;
  application?: Application;
  archived?: boolean;
  createdBy?: number;
  createdDate?: string;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  paymentMethod?: string;
  secretCode?: number;
}
