/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PromoterResponse {
  accountLocked?: boolean;
  dateOfBirth?: string;
  email?: string;
  enabled?: boolean;
  firstname?: string;
  lastname?: string;
  nationalIdNumber?: string;
  phoneNumber?: string;
}
