/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CourseResponse } from '../models/course-response';
import { SpecialityResponse } from '../models/speciality-response';
export interface SessionDetailsListResponse {
  courses?: Array<CourseResponse>;
  specialities?: Array<SpecialityResponse>;
}
