/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionResponse {
  examDate?: string;
  examType?: string;
  id?: number;
  sessionYear?: string;
}
