/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SpecialityResponse {
  code?: string;
  courseId?: number;
  courseName?: string;
  description?: string;
  examType?: string;
  id?: number;
  name?: string;
  paymentAmount?: number;
  trainingCenterName?: string;
}
