/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Application } from '../models/application';
import { Course } from '../models/course';
import { OffersSpeciality } from '../models/offers-speciality';
import { Subject } from '../models/subject';
export interface Speciality {
  actived?: boolean;
  applicationList?: Array<Application>;
  archived?: boolean;
  code?: string;
  course?: Course;
  createdBy?: number;
  createdDate?: string;
  description?: string;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  name?: string;
  offersSpecialityList?: Array<OffersSpeciality>;
  subjectList?: Array<Subject>;
}
