/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Campus } from '../models/campus';
import { OffersSpeciality } from '../models/offers-speciality';
export interface TrainingCenterResponse {
  acronym?: string;
  agreementFile?: Array<string>;
  agreementNumber?: string;
  campusList?: Array<Campus>;
  centerPresentCandidateForCqp?: boolean;
  centerPresentCandidateForDqp?: boolean;
  division?: string;
  endDateOfAgreement?: string;
  fullName?: string;
  offersSpecialityList?: Array<OffersSpeciality>;
  promoter?: string;
  promoterName?: string;
  startDateOfAgreement?: string;
  status?: 'READYTOPAY' | 'DRAFT' | 'PAID' | 'VALIDATED' | 'INCOMPLETED' | 'REJECTED' | 'PENDING';
}
