/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Campus } from '../models/campus';
import { Course } from '../models/course';
import { HasSchooled } from '../models/has-schooled';
import { OffersSpeciality } from '../models/offers-speciality';
import { TrainingCenterStatusHistory } from '../models/training-center-status-history';
export interface TrainingCenter {
  acronym?: string;
  actived?: boolean;
  agreementFileUrl?: string;
  agreementNumber?: string;
  agreementStatus?: string;
  archived?: boolean;
  campusList?: Array<Campus>;
  centerAge?: number;
  centerEmail?: string;
  centerPhone?: string;
  centerType?: string;
  city?: string;
  courseList?: Array<Course>;
  createdBy?: number;
  createdDate?: string;
  division?: string;
  endDateOfAgreement?: string;
  fullAddress?: string;
  fullName?: string;
  hasSchooledList?: Array<HasSchooled>;
  id?: number;
  internalRegulationFileUrl?: string;
  isCenterPresentCandidateForCqp?: boolean;
  isCenterPresentCandidateForDqp?: boolean;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  localisationFileUrl?: string;
  offersSpecialityList?: Array<OffersSpeciality>;
  region?: string;
  signatureLetterUrl?: string;
  startDateOfAgreement?: string;
  status?: TrainingCenterStatusHistory;
  website?: string;
}
