/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Campus } from '../models/campus';
import { OffersSpeciality } from '../models/offers-speciality';
export interface TrainingCenter {
  [x: string]: any;
  acronym?: string;
  actived?: boolean;
  agreementFileUrl?: string;
  agreementNumber?: string;
  agreementStatus?: string;
  archived?: boolean;
  campusList?: Array<Campus>;
  centerPresentCandidateForCqp?: boolean;
  centerPresentCandidateForDqp?: boolean;
  createdBy?: number;
  createdDate?: string;
  division?: string;
  endDateOfAgreement?: string;
  fullAddress?: string;
  fullName?: string;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  offersSpecialityList?: Array<OffersSpeciality>;
  startDateOfAgreement?: string;
}
