/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TrainingCenter } from '../models/training-center';
export interface TrainingCenterStatusHistory {
  actived?: boolean;
  archived?: boolean;
  comment?: string;
  createdBy?: number;
  createdDate?: string;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  status?: 'READYTOPAY' | 'DRAFT' | 'PAID' | 'VALIDATED' | 'INCOMPLETED' | 'REJECTED' | 'PENDING';
  trainingCenter?: TrainingCenter;
}
