/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Campus } from '../models/campus';
import { OffersSpeciality } from '../models/offers-speciality';
export interface TrainingCenter {
  acronym?: string;
  actived?: boolean;
  agreementFileUrl?: string;
  agreementNumber?: string;
  agreementStatus?: string;
  archived?: boolean;
  campusList?: Array<Campus>;
  centerAge?: number;
  centerEmail?: string;
  centerPhone?: string;
  centerType?: string;
  city?: string;
  createdBy?: number;
  createdDate?: string;
  division?: string;
  endDateOfAgreement?: string;
  fullAddress?: string;
  fullName?: string;
  id?: number;
  isCenterPresentCandidateForCqp?: boolean;
  isCenterPresentCandidateForDqp?: boolean;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  offersSpecialityList?: Array<OffersSpeciality>;
  region?: string;
  startDateOfAgreement?: string;
  website?: string;
}
