/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCenterRequest {
  capacity: number;
  division: string;
  examCenterId: number;
  name: string;
  region: string;
}
