/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateSessionRequest {
  examDate: string;
  examType: string;
  sessionId: number;
  sessionYear: string;
}
