/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCampusRequest {
  capacity: number;
  name: string;
  oldName: string;
  quarter: string;
  town: string;
  xcoor?: number;
  ycoor?: number;
}
