/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  dateOfBirth?: string;
  email?: string;
  firstname?: string;
  id?: number;
  lastname?: string;
  nationalIdNumber?: string;
  phoneNumber?: string;
  sex?: string;
}
