package com.jotsamikael.applycam.trainingCenter.division;

import java.util.List;
import java.util.Optional;

public record Division(String department, String region) {
    public static  final List<Division> ALL_CAMEROON_DIVISIONS = List.of(
            new Division("Mfoundi", "CENTER"),
            new Division("Haute-Sanaga", "CENTER"),
            new Division("Lekié", "CENTER"),
            new Division("Mbam-et-Inoubou", "CENTER"),
            new Division("Mbam-et-Kim", "CENTER"),
            new Division("Méfou-et-Afamba", "CENTER"),
            new Division("Méfou-et-Akono", "CENTER"),
            new Division("Nyong-et-Kéllé", "CENTER"),
            new Division("Nyong-et-Mfoumou", "CENTER"),
            new Division("Nyong-et-So'o", "CENTER"),
            new Division("Djerem", "ADAMAWA"),
            new Division("Faro-et-Deo", "ADAMAWA"),
            new Division("Mayo-Banyo", "ADAMAWA"),
            new Division("Mbéré", "ADAMAWA"),
            new Division("Vina", "ADAMAWA"),
            new Division("Boumba-et-Ngoko", "EAST"),
            new Division("Haut-Nyong", "EAST"),
            new Division("Kadey", "EAST"),
            new Division("Lom-et-Djerem", "EAST"),
            new Division("Diamaré", "FAR-NORTH"),
            new Division("Logone-et-Chari", "FAR-NORTH"),
            new Division("Mayo-Danay", "FAR-NORTH"),
            new Division("Mayo-Kani", "FAR-NORTH"),
            new Division("Mayo-Sava", "FAR-NORTH"),
            new Division("Mayo-Tsanaga", "FAR-NORTH"),
            new Division("Bamboutos", "WEST"),
            new Division("Haut-Nkam", "WEST"),
            new Division("Mifi", "WEST"),
            new Division("Menoua", "WEST"),
            new Division("Momo", "NORTH-WEST"),
            new Division("Mezam", "NORTH-WEST"),
            new Division("Bui", "NORTH-WEST"),
            new Division("Donga-Mantung", "NORTH-WEST"),
            new Division("Menchum", "NORTH-WEST"),
            new Division("Meme", "SOUTH-WEST"),
            new Division("Fako", "SOUTH-WEST"),
            new Division("Koupé-Manengouba", "SOUTH-WEST"),
            new Division("Lebialem", "SOUTH-WEST"),
            new Division("Manyu", "SOUTH-WEST"),
            new Division("Ndian", "SOUTH-WEST"),
            new Division("Benoue", "NORTH"),
            new Division("Mayo-Louti", "NORTH"),
            new Division("Mayo-Rey", "NORTH"),
            new Division("Fako", "SOUTH-WEST"),
            new Division("Ocean", "SOUTH"),
            new Division("Mvila", "SOUTH"),
            new Division("Dja-et-Lobo", "SOUTH"),
            new Division("Vallée-du-Ntem", "SOUTH"),
            new Division("Mfoundi", "CENTER"),
            new Division("Haute-Sanaga", "CENTER"),
            new Division("Lekié", "CENTER"),
            new Division("Mbam-et-Inoubou", "CENTER"),
            new Division("Mbam-et-Kim", "CENTER"),
            new Division("Méfou-et-Afamba", "CENTER"),
            new Division("Méfou-et-Akono", "CENTER"),
            new Division("Nyong-et-Kéllé", "CENTER"),
            new Division("Nyong-et-Mfoumou", "CENTER"),
            new Division("Nyong-et-So'o", "CENTER")
    );

}
