/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { candidateAppliance } from '../fn/application/candidate-appliance';
import { CandidateAppliance$Params } from '../fn/application/candidate-appliance';

@Injectable({ providedIn: 'root' })
export class ApplicationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `candidateAppliance()` */
  static readonly CandidateAppliancePath = '/application/apply/PersonalInformation';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `candidateAppliance()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  candidateAppliance$Response(params?: CandidateAppliance$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return candidateAppliance(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `candidateAppliance$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  candidateAppliance(params?: CandidateAppliance$Params, context?: HttpContext): Observable<{
}> {
    return this.candidateAppliance$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
