/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Division } from '../models/division';
import { getDivisionByRegion } from '../fn/division/get-division-by-region';
import { GetDivisionByRegion$Params } from '../fn/division/get-division-by-region';

@Injectable({ providedIn: 'root' })
export class DivisionService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getDivisionByRegion()` */
  static readonly GetDivisionByRegionPath = '/division/get-by-region/{region}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDivisionByRegion()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDivisionByRegion$Response(params: GetDivisionByRegion$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Division>>> {
    return getDivisionByRegion(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDivisionByRegion$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDivisionByRegion(params: GetDivisionByRegion$Params, context?: HttpContext): Observable<Array<Division>> {
    return this.getDivisionByRegion$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Division>>): Array<Division> => r.body)
    );
  }

}
