/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAuthenticatedUserInfo } from '../fn/user-controller/get-authenticated-user-info';
import { GetAuthenticatedUserInfo$Params } from '../fn/user-controller/get-authenticated-user-info';
import { UserResponse } from '../models/user-response';

@Injectable({ providedIn: 'root' })
export class UserControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAuthenticatedUserInfo()` */
  static readonly GetAuthenticatedUserInfoPath = '/user/info';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAuthenticatedUserInfo()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAuthenticatedUserInfo$Response(params?: GetAuthenticatedUserInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return getAuthenticatedUserInfo(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAuthenticatedUserInfo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAuthenticatedUserInfo(params?: GetAuthenticatedUserInfo$Params, context?: HttpContext): Observable<UserResponse> {
    return this.getAuthenticatedUserInfo$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

}
