/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SpecialityResponse } from '../../models/speciality-response';

export interface FindByName1$Params {
  name: string;
}

export function findByName1(http: HttpClient, rootUrl: string, params: FindByName1$Params, context?: HttpContext): Observable<StrictHttpResponse<SpecialityResponse>> {
  const rb = new RequestBuilder(rootUrl, findByName1.PATH, 'get');
  if (params) {
    rb.path('name', params.name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SpecialityResponse>;
    })
  );
}

findByName1.PATH = '/specialities/findByName/{name}';
