/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CandidateResponse } from '../../models/candidate-response';

export interface GetCandidateById$Params {

/**
 * ID du candidat
 */
  candidateId: number;
}

export function getCandidateById(http: HttpClient, rootUrl: string, params: GetCandidateById$Params, context?: HttpContext): Observable<StrictHttpResponse<CandidateResponse>> {
  const rb = new RequestBuilder(rootUrl, getCandidateById.PATH, 'get');
  if (params) {
    rb.path('candidateId', params.candidateId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CandidateResponse>;
    })
  );
}

getCandidateById.PATH = '/candidate/{candidateId}';
