/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseCandidateResponse } from '../../models/page-response-candidate-response';

export interface GetCandidatesOfConnectedpromoterid$Params {
  promoterId: number;
  year: number;
  offset?: number;
  pageSize?: number;
  field?: string;
  order?: boolean;
}

export function getCandidatesOfConnectedpromoterid(http: HttpClient, rootUrl: string, params: GetCandidatesOfConnectedpromoterid$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseCandidateResponse>> {
  const rb = new RequestBuilder(rootUrl, getCandidatesOfConnectedpromoterid.PATH, 'get');
  if (params) {
    rb.path('promoterId', params.promoterId, {});
    rb.path('year', params.year, {});
    rb.query('offset', params.offset, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('field', params.field, {});
    rb.query('order', params.order, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseCandidateResponse>;
    })
  );
}

getCandidatesOfConnectedpromoterid.PATH = '/candidate/{promoterId}/{year}';
