/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseExamCenterResponse } from '../../models/page-response-exam-center-response';

export interface FindByName4$Params {
  division: string;
  offset?: number;
  pageSize?: number;
  field?: string;
  order?: boolean;
}

export function findByName4(http: HttpClient, rootUrl: string, params: FindByName4$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseExamCenterResponse>> {
  const rb = new RequestBuilder(rootUrl, findByName4.PATH, 'get');
  if (params) {
    rb.path('division', params.division, {});
    rb.query('offset', params.offset, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('field', params.field, {});
    rb.query('order', params.order, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseExamCenterResponse>;
    })
  );
}

findByName4.PATH = '/assignment/findBy-division/{division}';
