/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetCanidateFileByType$Params {
  userId: number;
  fileType: string;
}

export function getCanidateFileByType(http: HttpClient, rootUrl: string, params: GetCanidateFileByType$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
  const rb = new RequestBuilder(rootUrl, getCanidateFileByType.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.path('fileType', params.fileType, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<string>>;
    })
  );
}

getCanidateFileByType.PATH = '/files/candidate-files/{userId}/{fileType}';
