/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseCampusResponse } from '../../models/page-response-campus-response';

export interface FindCampusByTown$Params {
  town: string;
  offset?: number;
  pageSize?: number;
  field?: string;
  order?: boolean;
}

export function findCampusByTown(http: HttpClient, rootUrl: string, params: FindCampusByTown$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseCampusResponse>> {
  const rb = new RequestBuilder(rootUrl, findCampusByTown.PATH, 'get');
  if (params) {
    rb.path('town', params.town, {});
    rb.query('offset', params.offset, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('field', params.field, {});
    rb.query('order', params.order, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseCampusResponse>;
    })
  );
}

findCampusByTown.PATH = '/campus/get-campus-by-training-town/{town}';
