/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseApplicationResponse } from '../../models/page-response-application-response';

export interface GetAllApplications$Params {

/**
 * Offset de pagination
 */
  offset?: number;

/**
 * Taille de page
 */
  pageSize?: number;

/**
 * Champ de tri
 */
  field?: string;

/**
 * Ordre de tri
 */
  order?: boolean;

/**
 * Statut de filtrage
 */
  status?: string;

/**
 * Type d'examen
 */
  examType?: string;

/**
 * Région
 */
  region?: string;

/**
 * Année
 */
  year?: string;
}

export function getAllApplications(http: HttpClient, rootUrl: string, params?: GetAllApplications$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseApplicationResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllApplications.PATH, 'get');
  if (params) {
    rb.query('offset', params.offset, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('field', params.field, {});
    rb.query('order', params.order, {});
    rb.query('status', params.status, {});
    rb.query('examType', params.examType, {});
    rb.query('region', params.region, {});
    rb.query('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseApplicationResponse>;
    })
  );
}

getAllApplications.PATH = '/application/get-all';
