/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UploadCandidateFile$Params {
      body?: {

/**
 * Fichier CNI
 */
'cniFile': Blob;

/**
 * Certificat de naissance
 */
'birthCertificate': Blob;

/**
 * Diplôme
 */
'diplomFile': Blob;

/**
 * Photo
 */
'photo': Blob;

/**
 * Ancienne candidature
 */
'oldApplyanceFile'?: Blob;

/**
 * Certificat de stage
 */
'stageCertificate'?: Blob;

/**
 * CV
 */
'cv'?: Blob;

/**
 * Justification financière
 */
'financialJustification'?: Blob;

/**
 * Lettre de motivation
 */
'letter'?: Blob;
}
}

export function uploadCandidateFile(http: HttpClient, rootUrl: string, params?: UploadCandidateFile$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, uploadCandidateFile.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

uploadCandidateFile.PATH = '/application/PersonalInformation/documents';
