/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateCourseAndAssignRequest } from '../../models/create-course-and-assign-request';

export interface CreateAndAssignCourseToActivitySector$Params {
      body: CreateCourseAndAssignRequest
}

export function createAndAssignCourseToActivitySector(http: HttpClient, rootUrl: string, params: CreateAndAssignCourseToActivitySector$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, createAndAssignCourseToActivitySector.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

createAndAssignCourseToActivitySector.PATH = '/course-management/create-and-assign';
