/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CourseResponse } from '../../models/course-response';

export interface SearchCoursesByName$Params {

/**
 * Nom à rechercher
 */
  name: string;
}

export function searchCoursesByName(http: HttpClient, rootUrl: string, params: SearchCoursesByName$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CourseResponse>>> {
  const rb = new RequestBuilder(rootUrl, searchCoursesByName.PATH, 'get');
  if (params) {
    rb.query('name', params.name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CourseResponse>>;
    })
  );
}

searchCoursesByName.PATH = '/course-management/search';
