/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateSpecialityRequest } from '../../models/create-speciality-request';

export interface CreateAndLinkSpecialityToTrainingCenter$Params {
  courseName: string;
  agreementNumber: string;
      body: CreateSpecialityRequest
}

export function createAndLinkSpecialityToTrainingCenter(http: HttpClient, rootUrl: string, params: CreateAndLinkSpecialityToTrainingCenter$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, createAndLinkSpecialityToTrainingCenter.PATH, 'post');
  if (params) {
    rb.path('courseName', params.courseName, {});
    rb.query('agreementNumber', params.agreementNumber, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

createAndLinkSpecialityToTrainingCenter.PATH = '/auth/create-and-link/{courseName}';
