/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UploadPromoterFile$Params {
  'approval-Number': string;

/**
 * Agreement file to upload
 */
  email: string;
  centerMail: string;
      body?: {
'cniFile': Blob;
'approvalFile': Blob;
'promoterPhoto': Blob;
'engagementLetter': Blob;
'locationPlan': Blob;
'internalRegulation'?: Blob;
}
}

export function uploadPromoterFile(http: HttpClient, rootUrl: string, params: UploadPromoterFile$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, uploadPromoterFile.PATH, 'post');
  if (params) {
    rb.path('approval-Number', params['approval-Number'], {});
    rb.path('email', params.email, {});
    rb.path('centerMail', params.centerMail, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

uploadPromoterFile.PATH = '/auth/promoter-register/documents/{approval-Number}/{email}/{centerMail}';
