/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SessionResponse } from '../../models/session-response';

export interface FindByName2$Params {
  examDate: string;
}

export function findByName2(http: HttpClient, rootUrl: string, params: FindByName2$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SessionResponse>>> {
  const rb = new RequestBuilder(rootUrl, findByName2.PATH, 'get');
  if (params) {
    rb.path('examDate', params.examDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SessionResponse>>;
    })
  );
}

findByName2.PATH = '/session/findBy-examdate/{examDate}';
