spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/applycam
    url: jdbc:mysql://localhost:3306/applycam
    username: root
    #username: username
    #password: password
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-plateform: org.hibernate.dialect.MysqlDialect
  mail:
    host: localhost
   # host: smtp.gmail.com
    #host:  ${EMAIL_HOSTNAME}

    port: 1025
   # port: 465
    username: 
#    username: jotsamikael@gmail.com
    #username:  ${EMAIL_USER_NAME}
    password: 
#    password: bmutcptpxacspogj
   # password:  ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: false
          ssl:
            enable: false
        starttls:
          enable: true
    protocol: smtp
application:
  security:
    jwt:
      secret-key: 2B29B84463A7EFE461D854B6345AF2B29B84463A7EFE461D854B6345AF
      expiration: 7788775678899780874
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  cors:
    origins: http://localhost:4200,http://localhost:8080 
  file:
    upload:
      files-output-path: ./uploads

server:
  port: 8088